package com.gu.playpasskeyauth.models

import com.webauthn4j.util.Base64UrlUtil
import play.api.libs.json.{JsString, Writes}

/** Type-safe wrapper for passkey (credential) identifiers.
  *
  * Passkey IDs are byte arrays that uniquely identify a WebAuthn credential. They are generated by the authenticator
  * during registration and used to identify the credential during authentication.
  *
  * This case class provides type safety to prevent accidentally mixing up passkey IDs with other byte arrays.
  *
  * @param bytes
  *   The credential ID bytes from the WebAuthn API (must not be null or empty)
  * @throws IllegalArgumentException
  *   if bytes is null or empty
  * @example
  *   {{{
  * // Create from raw bytes (e.g., from WebAuthn API)
  * val passkeyId = PasskeyId(credentialIdBytes)
  *
  * // Create from base64url string (e.g., from database)
  * val passkeyId = PasskeyId.fromBase64Url(storedId)
  *
  * // Convert back to base64url for storage
  * val storedId = passkeyId.toBase64Url
  *   }}}
  */
case class PasskeyId(bytes: Array[Byte]) {
  require(bytes != null && bytes.nonEmpty, "PasskeyId must not be null or empty")

  /** Returns the base64url-encoded string representation.
    *
    * Use this for storage in databases or transmission in JSON.
    */
  def toBase64Url: String = Base64UrlUtil.encodeToString(bytes)

  // Override equals and hashCode for proper Array[Byte] comparison
  override def equals(obj: Any): Boolean = obj match {
    case that: PasskeyId => java.util.Arrays.equals(this.bytes, that.bytes)
    case _               => false
  }

  override def hashCode(): Int = java.util.Arrays.hashCode(bytes)

  override def toString: String = s"PasskeyId($toBase64Url)"
}

object PasskeyId {

  /** Creates a PasskeyId from a base64url-encoded string.
    *
    * @param encoded
    *   The base64url-encoded credential ID (must not be null or empty)
    * @return
    *   A type-safe PasskeyId
    * @throws IllegalArgumentException
    *   if encoded is null, empty, or not valid base64url
    */
  def fromBase64Url(encoded: String): PasskeyId = {
    require(encoded != null && encoded.nonEmpty, "PasskeyId base64url string must not be null or empty")
    PasskeyId(Base64UrlUtil.decode(encoded))
  }

  given Writes[PasskeyId] = Writes { id => JsString(id.toBase64Url) }
}
