package com.gu.playpasskeyauth.models

import com.webauthn4j.util.Base64UrlUtil
import play.api.libs.json.{JsString, Writes}

/** Type-safe wrapper for passkey (credential) identifiers.
  *
  * Passkey IDs are byte arrays that uniquely identify a WebAuthn credential. They are generated by the authenticator
  * during registration and used to identify the credential during authentication.
  *
  * This opaque type provides type safety to prevent accidentally mixing up passkey IDs with other byte arrays, while
  * having zero runtime overhead.
  *
  * @example
  *   {{{
  * // Create from raw bytes (e.g., from WebAuthn API)
  * val passkeyId = PasskeyId(credentialIdBytes)
  *
  * // Create from base64url string (e.g., from database)
  * val passkeyId = PasskeyId.fromBase64Url(storedId)
  *
  * // Convert back to base64url for storage
  * val storedId = passkeyId.toBase64Url
  *   }}}
  */
opaque type PasskeyId = Array[Byte]

object PasskeyId:

  /** Creates a PasskeyId from raw bytes.
    *
    * @param bytes
    *   The credential ID bytes from the WebAuthn API (must not be null or empty)
    * @return
    *   A type-safe PasskeyId
    * @throws IllegalArgumentException
    *   if bytes is null or empty
    */
  def apply(bytes: Array[Byte]): PasskeyId =
    require(bytes != null && bytes.nonEmpty, "PasskeyId must not be null or empty")
    bytes

  /** Creates a PasskeyId from a base64url-encoded string.
    *
    * @param encoded
    *   The base64url-encoded credential ID (must not be null or empty)
    * @return
    *   A type-safe PasskeyId
    * @throws IllegalArgumentException
    *   if encoded is null, empty, or not valid base64url
    */
  def fromBase64Url(encoded: String): PasskeyId =
    require(encoded != null && encoded.nonEmpty, "PasskeyId base64url string must not be null or empty")
    Base64UrlUtil.decode(encoded)

  given Writes[PasskeyId] = Writes { id => JsString(id.toBase64Url) }

  /** Extension methods for PasskeyId */
  extension (passkeyId: PasskeyId)
    /** Returns the underlying byte array.
      *
      * Use this when you need to pass the ID to the WebAuthn library or other APIs expecting raw bytes.
      */
    def bytes: Array[Byte] = passkeyId

    /** Returns the base64url-encoded string representation.
      *
      * Use this for storage in databases or transmission in JSON.
      */
    def toBase64Url: String = Base64UrlUtil.encodeToString(passkeyId)
